version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  reservation-service:
    image: reservation-service
    build:
      context: ./Backend/ReservationService
      dockerfile: Dockerfile
    ports:
      - "9001:80"
    depends_on:
      - mongodb
    environment:
      - ConnectionStrings:MongoDB=mongodb://mongodb:27017

  movie-service:
    image: movie-service
    build:
      context: ./Backend/MovieRental
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - mongodb
    environment:
      - ConnectionStrings:MongoDB=mongodb://mongodb:27017
      
  front:
    image: front
    build:
      context: ./front
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9002:8080"
      
    